### ISSUE TITLE
"A required class is missing" Error

### ISSUE THREAD

**Issue by kensully** [ps3mediaserver/ps3mediaserver#133]
Hi,
First of all I congratulate all those who contributed to this project.
When I try to compile the project I get `A required class is missing: org/apache/maven/plugin/install/AbstractInstallMojo`

I am on Ubuntu 14.04 platform and I have `java version "1.7.0_75"`

I issued below commands to compile it:

     mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external
     mvn com.savage7.maven.plugins:maven-external-dependency-plugin:install-external
     mvn package

Would you help me fix it?

Regards.
Kenn

**Comment by taconaut** [comment]
Hi Kenn,

Which maven version are you using?
I'm using maven 3.2.3, java 8u40 on a win7 machine and it's working fine.

**Comment by kensully** [comment]
Hi Taconaut,
Thank you for responding.
I had older version of maven (version 2.2) I upgraded it but I got some different errors. After I removed /home/$USER/.m2 folder it compiled successfully.
Regards.
Kenn
