### ISSUE TITLE
Broken link in the README file

### ISSUE THREAD

**Issue by ericshawlinux** [ps3mediaserver/ps3mediaserver#136]
In the readme file displayed here on github, there is a broken link located under Installation > "For Debian and Ubuntu packages, see here. "

**Comment by Nadahar** [comment]
@ericshawlinux I think the project has been abandoned for quite a while, the last months even the [forum](http://www.ps3mediaserver.org/forum/) has went offline.

[Universal Media Server](https://github.com/UniversalMediaServer/UniversalMediaServer) is a fork that is still active, but no packages for any Linux distro exists that I'm aware of. [Installing manually under Linux](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions) isn't that difficult though.

**Comment by ericshawlinux** [comment]
oh that sucks, I was trying to use this
